function proportionComparisonChosen = importfileForFigure2(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PROPORTIONCOMPARISONCHOSEN = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  PROPORTIONCOMPARISONCHOSEN = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  proportionComparisonChosen = importfile("proportionComparisonChosen.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Aug-2020 18:50:47

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 73);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Subject", "CNSU_0002", "CNSU_1", "CNSU_2", "CNSU_3", "CNSU_4", "CNSU_5", "CNSU_6", "CNSU_7", "CNSU_8", "CNSU_9", "CNSU_10", "CNSU_11", "CNSU_12", "CNSU_13", "CNSU_14", "CNSU_15", "CNSU_16", "CNSU_17", "CNSU_0004", "CNSU_18", "CNSU_19", "CNSU_20", "CNSU_21", "CNSU_22", "CNSU_23", "CNSU_24", "CNSU_25", "CNSU_26", "CNSU_27", "CNSU_28", "CNSU_29", "CNSU_30", "CNSU_31", "CNSU_32", "CNSU_33", "CNSU_34", "CNSU_0008", "CNSU_35", "CNSU_36", "CNSU_37", "CNSU_38", "CNSU_39", "CNSU_40", "CNSU_41", "CNSU_42", "CNSU_43", "CNSU_44", "CNSU_45", "CNSU_46", "CNSU_47", "CNSU_48", "CNSU_49", "CNSU_50", "CNSU_51", "CNSU_0017", "CNSU_52", "CNSU_53", "CNSU_54", "CNSU_55", "CNSU_56", "CNSU_57", "CNSU_58", "CNSU_59", "CNSU_60", "CNSU_61", "CNSU_62", "CNSU_63", "CNSU_64", "CNSU_65", "CNSU_66", "CNSU_67", "CNSU_68"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
proportionComparisonChosen = readtable(filename, opts);

end